### ISSUE TITLE
Malformed Input Exception

### ISSUE THREAD

**Issue by maso222** [Proximity-Engine/Proximity#40]
using version 0.5.2

getting an error using long dash in type_line override 
the below type line was copied from scryfall and the word Creature removed but throws error due to an issue with the long dash

Ertai, the Corrupted --override=type_line:"Legendary — Phyrexian Human Wizard"

java.nio.charset.MalformedInputException: Input length = 1
        at java.base/java.nio.charset.CoderResult.throwException(CoderResult.java:274)
        at java.base/sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
        at java.base/sun.nio.cs.StreamDecoder.read(StreamDecoder.java:188)
        at java.base/java.io.InputStreamReader.read(InputStreamReader.java:177)
        at java.base/java.io.BufferedReader.fill(BufferedReader.java:162)
        at java.base/java.io.BufferedReader.readLine(BufferedReader.java:329)
        at java.base/java.io.BufferedReader.readLine(BufferedReader.java:396)
        at dev.hephaestus.proximity.Main.loadCardsFromFile(Main.java:74)
        at dev.hephaestus.proximity.Main.lambda$main$2(Main.java:57)
        at dev.hephaestus.proximity.util.Result.then(Result.java:45)
        at dev.hephaestus.proximity.Main.main(Main.java:56)

**Comment by Haven-King** [comment]
Is there a reason you need to override it to that? His type line should already be that.

**Comment by maso222** [comment]
I was just trying to shorten it since as is it is very long and runs off the card. I can just use the short dash for now though, not a huge deal

**Comment by Haven-King** [comment]
Oh, I didn't see that you omitted "creature". This should work:
```
Ertai, the Corrupted --override=type_line:"Legendary \u2014 Phyrexian Human Wizard"
```
That's the escaped unicode character code.

**Comment by maso222** [comment]
Ahh okay, makes sense. Thank you
